# Configuración principal
covid.report.date=2020-04-16
covid.report.iso=USA

# Configuración de base de datos
db.url=jdbc:mysql://localhost:3306/covid_db
db.user=root
db.password=admin

# Configuración de API externa
api.key=b444ef1fffmshdf0295dcb01d536p108cf1jsnea6d75e5c08d
api.host=covid-19-statistics.p.rapidapi.com